version: '3'

services:
  letterboxd_collage:
    image: letterboxd_collage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    environment:
      REMOTE_SELENIUM_ADDRESS: "http://selenium:4444/wd/hub"
      SELENIUM_REQUESTS_PROXY_HOST: "192.168.101.2"
